#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    location / {
        add_header X-Served-By $HOSTNAME;
    }
}' | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
