#!/usr/bin/env bash
# This script displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

var=0

while [ $var -le 10 ];
do
   if [ $var -eq 4 ];
     then
         echo "bad luck"
    elif [ $var -eq 8 ];
        then
            echo "good luck"
    else
             echo "Best School"
    fi
        ((var++))
done         
