#!/usr/bin/env bash
# This script displays numbers with superstitions

# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

var=0

while [ $var -le 20 ];
  do
    case "$var" in
    4)
       echo "$var"
       echo "Bad luck from china"
       ;;
    9)
       echo "$var"
       echo "Bad luck from japan"
       ;;
    17)
       echo "$var"
       echo "bad luck from Italy"
       ;;
    *)
       echo "$var"
    ;;
    esac
    ((var++))
done
